SOL-38 [Integrate] Integrate smart contract function for viewing only  their campaigns
framgia/sph-solidity pull request #19
Opened 2023-07-04 08:23 UTC by kenorenzsun

## Issue Link
-[ Backlog link](https://framgiaph.backlog.com/view/SPH_SOLIDITY-38)

## Target Page | Component | Function
- /profile

## Pre-condition
- set your .env in fe subdire 
`CONTRACT_ADDRESS = "0x7E4DA45093Ff3B25609301369060c15563eA6aEF"`

## Steps | Commands
1. Add here

## Expected Output
- user should be able to view his/her campaigns 

## Definition of Done
- Add here

## Test View Points
- [ ] Add here

## Notes
N/A

## Screenshots | Recordings
[Screencast 2023-07-04 16-20-15.webm](https://github.com/framgia/sph-solidity/assets/116168014/86517d96-4b64-485b-b8b2-5587d16f80ff)

## Code Review

### General
- [ ] Does the code meet the requirements of the project?
- [ ] Is the code readable and maintainable?
- [ ] Are there any unnecessary or redundant lines of code?
- [ ] Are there any long methods or functions that should be refactored?
- [ ] Are there any performance issues?

### Functionality
- [ ] Are there any logical errors?
- [ ] Are edge cases handled properly?
- [ ] Are there any potential security vulnerabilities?

### Code Style
- [ ] Does the code adhere to the project's coding standards?
- [ ] Are variable and function names descriptive and meaningful?
- [ ] Is there proper use of comments and documentation?
- [ ] Is the code properly formatted? Are indentation, spacing, and formatting consistent?

### Security
- [ ] Is the website secure from common attacks?
- [ ] Are inputs properly validated and sanitized?
- [ ] Are sensitive data and credentials properly protected?

### Testing
- [ ] Are there sufficient test cases?
- [ ] Do the test cases cover all functionality?
- [ ] Are the test cases properly written and documented?

### Additional Comments
- [ ] Are there any other issues or concerns with the code?
- [ ] Are there any suggestions for improvement?
- [ ] Are there any positive aspects of the code that should be highlighted?

2023-07-04 09:12 UTC, chevyB requested changes

2023-07-04 09:12 UTC, chevyB commented on fe/src/composables/useUtils.ts
> +    const timeDiff = dateNew.getTime() - dateNow.getTime();
put type on every variables
```suggestion
    const dateNow: Date = new Date();
    const dateNew: Date = new Date(Number(dateInt) * 1000);
    const timeDiff : Date = dateNew.getTime() - dateNow.getTime();
```

2023-07-04 09:12 UTC, chevyB commented on fe/src/pages/profile.vue
> +const useWallet: any = useWalletStore();
dont use any
```suggestion
import { useWalletStore, WalletStore } from "~/store/wallet";
const useWallet: WalletStore = useWalletStore();
```

2023-07-04 09:12 UTC, chevyB commented on fe/src/pages/profile.vue
> +const imgSrc = `https://api.multiavatar.com/${address}.png`;
provide data type

2023-07-04 09:12 UTC, chevyB commented on fe/src/pages/profile.vue
> +        userCampaigns.value = result.map((campaign: any) => {
dont use `any` type

2023-07-04 09:12 UTC, chevyB commented on fe/src/pages/profile.vue
> +      .catch((error) => {
put data type

2023-07-04 10:19 UTC, arden-dave submitted a review, later dismissed

2023-07-05 05:52 UTC, kenorenzsun commented on fe/src/pages/profile.vue
> +const useWallet: any = useWalletStore();
I just removed the type sir because types are already set in the useWalletStore

2023-07-05 08:25 UTC, kenorenzsun commented on fe/src/pages/profile.vue
> +const imgSrc = `https://api.multiavatar.com/${address}.png`;
![image](https://github.com/framgia/sph-solidity/assets/116168014/3c385269-b6e6-4ca4-8499-1a4e50bba349)

2023-07-05 09:48 UTC, ipilikent commented
## Approved PR
- The pagination is working & displayed
- The new campaign created by the user will be displayed in his My Campaign tab

## Proof
<details>

![Sol- 38 Integrate Viewing only their campaigns](https://github.com/framgia/sph-solidity/assets/110364019/9a285ae8-6bf6-45e6-9c3f-3101b6117714)

</details>

Test Case: https://docs.google.com/spreadsheets/d/114GrEn-LQQ8saIvjz9zqenuk05qmO4dN/edit#gid=1122662191
-----
- Total Test time: 0.75 hr.
- Total Comments: 0
- Total Iterations: 0

2023-07-05 09:49 UTC, ipilikent approved these changes

2023-07-05 10:02 UTC, arden-dave approved these changes

2023-07-05 10:07 UTC, chevyB approved these changes

2023-07-05 10:28 UTC, merged