SOL-51 [Integrate] Integrate smart contract function for sending donation to a campaign
framgia/sph-solidity pull request #25
Opened 2023-07-06 09:51 UTC by kenorenzsun

## Issue Link
- Backlog link https://framgiaph.backlog.com/view/SPH_SOLIDITY-51

## Target Page | Component | Function
- `/campaigns/{id}`

## Pre-condition
- none

## Steps | Commands
1. Add here

## Expected Output
- Add here

## Definition of Done
- Create a campaign then get its **id** 
- then put it in the `{id}` of `/campaigns/{id}`
- then input a donation and submit
- after successful donation go to profile page and you will see the amount donated
## Test View Points
- [ ] Add here

## Notes
N/A

## Screenshots | Recordings
[Screencast 2023-07-06 17-46-37.webm](https://github.com/framgia/sph-solidity/assets/116168014/43affbfc-7e74-4a3b-83b5-5fee9636cb59)

## Code Review

### General
- [ ] Does the code meet the requirements of the project?
- [ ] Is the code readable and maintainable?
- [ ] Are there any unnecessary or redundant lines of code?
- [ ] Are there any long methods or functions that should be refactored?
- [ ] Are there any performance issues?

### Functionality
- [ ] Are there any logical errors?
- [ ] Are edge cases handled properly?
- [ ] Are there any potential security vulnerabilities?

### Code Style
- [ ] Does the code adhere to the project's coding standards?
- [ ] Are variable and function names descriptive and meaningful?
- [ ] Is there proper use of comments and documentation?
- [ ] Is the code properly formatted? Are indentation, spacing, and formatting consistent?

### Security
- [ ] Is the website secure from common attacks?
- [ ] Are inputs properly validated and sanitized?
- [ ] Are sensitive data and credentials properly protected?

### Testing
- [ ] Are there sufficient test cases?
- [ ] Do the test cases cover all functionality?
- [ ] Are the test cases properly written and documented?

### Additional Comments
- [ ] Are there any other issues or concerns with the code?
- [ ] Are there any suggestions for improvement?
- [ ] Are there any positive aspects of the code that should be highlighted?

2023-07-06 10:32 UTC, chevyB requested changes

2023-07-06 10:32 UTC, chevyB commented on fe/src/components/campaign/fund-form.vue
> +        "
Can we add this logic of isLoading class to the basebutton component instead? 
Then pass `isLoading` props

2023-07-06 10:32 UTC, chevyB commented on fe/src/components/campaign/fund-form.vue
> +    warning();
i think no need to create a function for now. Unless it has so many content

2023-07-06 10:32 UTC, chevyB commented on fe/src/pages/campaigns/[id].vue
> +const donateCampaign = async (amount: number) => {
```suggestion
const donateCampaign = async (amount: number) : void => {
```

2023-07-07 03:30 UTC, wylenjoan reviewed
Can you make the cards in `My Campaigns` tab of Profile page clickable and redirect to individual Campaign page? 🙇

2023-07-07 03:46 UTC, chevyB commented on fe/src/components/campaign/fund-form.vue
> +      </BaseButton>
The new props is not really used by others.
Maybe you can create a new reusable button that is calling basebutton. Like this:

const defaultClasss= 'btn-gradient-hr'
const loadingClass = 'bg-disabled h-9 px-4 rounded-[6px] text-white'
<NewButton>
<BaseButton
        type="submit"
        :class="isLoading ? loadingClass : defaultClass"
        :disabled="isLoading"
      >
<NewButton>

Above is only applicable if you think there will be similar button in the future.
Else, revert the changes

2023-07-07 03:54 UTC, chevyB submitted a review, later dismissed

2023-07-07 06:00 UTC, wylenjoan approved these changes, later dismissed
Approved :white_check_mark:
Review time: 30 mins
Comment: 1
Iteration: 1
Working:
<details>
<summary> Can send donation to campaign </summary>

![image](https://github.com/framgia/sph-solidity/assets/57890826/cc90099e-fe8b-422e-9897-c90c24664628)

![image](https://github.com/framgia/sph-solidity/assets/57890826/2c7e2a56-35f4-4c70-977c-197b281cd638)

</details>

2023-07-07 07:09 UTC, ipilikent commented
Comment
• Problem
![1](https://github.com/framgia/sph-solidity/assets/110364019/113ca1b6-e166-4789-a431-839d4160f07b)

• Expected Output
- Fund rejected! - when reject
- Funding campaign in progress! when confirm
- Fund successfully send! - finish sent
- Letters cannot be input

2023-07-07 10:26 UTC, ipilikent commented
## Approved PR
- The user can send donation in the campaign
- The validation messages are correct and working 
- Can input in the fund field
- The button is working
- After successful donation go to profile page and you will see the amount donated

## Proof
<details>

![Sol- 51 Integrate sending donation](https://github.com/framgia/sph-solidity/assets/110364019/4db81e69-9879-4261-b7f3-a4ca3323b954)

</details>

Test Case: https://docs.google.com/spreadsheets/d/114GrEn-LQQ8saIvjz9zqenuk05qmO4dN/edit#gid=896446223
-----
- Total Test time:  1 hr.
- Total Comments: 1
- Total Iterations: 1

2023-07-07 10:27 UTC, ipilikent approved these changes

2023-07-07 10:30 UTC, wylenjoan approved these changes

2023-07-07 10:35 UTC, chevyB approved these changes

2023-07-07 10:35 UTC, merged